[package]
name = "distance-util"
version = "0.3.1"
authors = ["Brian Bowman <seeker14491@gmail.com>"]
edition = "2021"

[dev-dependencies]
version-sync = "0.9"

[dependencies]
serde = { version = "1", optional = true, features = ["derive"] }
thousands = "0.2"
