[package]
name = "distance-util"
version = "0.0.3"
authors = ["Brian Bowman <seeker14491@gmail.com>"]
edition = "2018"

[dependencies]
enumflags2 = "0.5.2"
enumflags2_derive = "0.5.0"
num-integer = "0.1.41"
serde = { version = "1.0.94", optional = true, features = ["derive"] }
thousands = "0.1.2"
