[package]
name = "distance-util"
version = "0.0.5"
authors = ["Brian Bowman <seeker14491@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
thousands = "0.1.2"
