pub const SPRINT: &[&str] = &[
    "Broken Symmetry",
    "Lost Society",
    "Negative Space",
    "Departure",
    "Ground Zero",
    "Amusement",
    "The Observer Effect",
    "Uncanny Valley",
    "Aftermath",
    "Friction",
    "The Thing About Machines",
    "Corruption",
    "Dissolution",
    "Falling Through",
    "Monolith",
    "Destination Unknown",
    "Rooftops",
    "The Manor",
    "Factory",
    "Stronghold",
    "Approach",
    "Chroma",
    "Cataclysm",
    "Diversion",
    "Euphoria",
    "Entanglement",
    "Automation",
    "Abyss",
    "Embers",
    "Isolation",
    "Repulsion",
    "Compression",
    "Research",
    "Contagion",
    "Overload",
    "Ascension",
    "Forgotten Utopia",
    "A Deeper Void",
    "Eye of the Storm",
    "The Sentinel Still Watches",
    "Pulse of a Violent Heart",
    "Shadow of the Beast",
    "It Was Supposed To Be Perfect",
    "Continuum",
    "Monument",
    "Brink",
    "Virtual Rift",
    "SR Motorplex",
    "Neo Seoul II",
    "Escape",
    "COAT Speedway",
    "Incline",
    "Tharsis Tholus",
    "Le Teleputo",
    "Neo Seoul",
    "Fulcrum",
    "Hard Light Transfer",
    "Observatory",
    "Digital",
    "Iris",
    "Precept",
    "Station",
    "Resonance",
    "Deterrence",
    "Terminus",
    "Projection",
    "Eclipse",
    "Vibe",
    "Luminescence",
    "Sector 0",
    "White Lightning Returns",
    "Micro",
    "Serenity",
    "Liminal",
    "Affect",
    "Beta Echoes",
    "Binary Construct",
    "Candles of Hekate",
    "Cosmic Glitch",
    "Epicentre",
    "Event Horizon",
    "Fallback Protocol",
    "Fiber",
    "Forsaken Shrine",
    "Gravity",
    "Hardline",
    "Impulse",
    "Industrial Fury",
    "Inferno",
    "Instability",
    "Knowledge",
    "Mentality",
    "Method",
    "Moonlight",
    "Noir",
    "Outrun",
    "Overdrive",
    "Paradise Lost",
    "Particular Journey",
    "Past",
    "Red",
    "Ruin",
    "Sea",
    "Sender",
    "Shafty",
    "Shallow",
    "Shrine",
    "Static Fire Signal",
    "Sugar Rush",
    "Sword",
    "Tetreal",
    "The Night Before",
    "Turbines",
    "Vector Valley",
    "Volcanic Rush",
    "Whisper",
    "White",
    "Wired",
    "Yellow",
    "Zenith",
];

pub const STUNT: &[&str] = &[
    "Neon Park",
    "Quantum Core",
    "Space Skate",
    "Stunt Playground",
    "Spooky Town",
    "Atrium",
    "Stuntware 2051",
    "Syncopation",
    "Canopy",
    "Fleeting Images",
];

pub const CHALLENGE: &[&str] = &[
    "Dodge",
    "Thunder Struck",
    "Grinder",
    "Descent",
    "Detached",
    "Red Heat",
    "Disassembly Line",
    "Elevation",
    "Obsidian",
    "Variant Blue",
    "Divide",
    "Electric",
    "44 Second Theory",
    "Biotec 4",
    "Hexahorrific",
    "Transfer",
];
